// <auto-generated />
using System;
using Games_Store.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Games_Store.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416060921_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Games_Store.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "An open-world action RPG set in a dystopian future city.",
                            Genre = "RPG",
                            ImageUrl = "https://placehold.co/300x400/1a1a2e/e94560?text=Cyber+Warriors",
                            IsFeatured = true,
                            Price = 59.99m,
                            Rating = 4.7999999999999998,
                            ReleaseDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cyber Warriors 2077"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A dark fantasy adventure with intense combat mechanics.",
                            Genre = "Action",
                            ImageUrl = "https://placehold.co/300x400/16213e/0f3460?text=Shadow+Legends",
                            IsFeatured = true,
                            Price = 49.99m,
                            Rating = 4.5,
                            ReleaseDate = new DateTime(2024, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Shadow Legends"
                        },
                        new
                        {
                            Id = 3,
                            Description = "High-speed racing with realistic physics and stunning tracks.",
                            Genre = "Racing",
                            ImageUrl = "https://placehold.co/300x400/1b1b2f/e43f5a?text=Racing+Thunder",
                            IsFeatured = false,
                            Price = 39.99m,
                            Rating = 4.2000000000000002,
                            ReleaseDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Racing Thunder"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Lead your fleet through space in this epic strategy game.",
                            Genre = "Strategy",
                            ImageUrl = "https://placehold.co/300x400/0a1931/185adb?text=Galaxy+Commander",
                            IsFeatured = true,
                            Price = 44.99m,
                            Rating = 4.7000000000000002,
                            ReleaseDate = new DateTime(2024, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Galaxy Commander"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Explore procedurally generated dungeons full of traps and treasures.",
                            Genre = "RPG",
                            ImageUrl = "https://placehold.co/300x400/2d132c/c72c41?text=Dungeon+Crawler",
                            IsFeatured = false,
                            Price = 29.99m,
                            Rating = 4.0,
                            ReleaseDate = new DateTime(2023, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Dungeon Crawler"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Build and manage the ultimate football team to glory.",
                            Genre = "Sports",
                            ImageUrl = "https://placehold.co/300x400/1a1a40/4834d4?text=Football+Manager",
                            IsFeatured = false,
                            Price = 34.99m,
                            Rating = 3.8999999999999999,
                            ReleaseDate = new DateTime(2024, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Football Manager Pro"
                        });
                });

            modelBuilder.Entity("Games_Store.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
